#!/bin/sh
#
# file : /sbin/mkinitramfs
# part of https://github.com/remsnet/xen-tools/tree/master/hooks/opensuse-13.1.d/24-setup-initramfs
#
# v0.8 - june 2014
# Author : Remsnet Consulting & internet Services LTD
#          horst.venzke@remsnet.de
# License : LGPL v2


# ENV
KERNEL_VERSION=`ls /boot/vmlinuz-* | xargs | awk -F " " '{ print $1 }' | sed "s#/boot/vmlinuz-##"`
BOOT=/boot
INITRAMFS_FILE=$BOOT/initramfs.img-$KERNEL_VERSION
DATADIR=/usr/share/mkinitramfs
INITIN=init.in
CPIOBIN=/usr/bin/cpio
GZIPBIN=/usr/bin/gzip

WDIR=$(mktemp -d /tmp/initrd-work.XXXXXXXXXX)
unsorted=$(mktemp /tmp/unsorted.XXXXXXXXXX)
binfiles="sh cat cp dd killall ls  mkdir mknod mount umount sed sleep ln rm uname"
sbinfiles="modprobe udevadm blkid switch_root mdadm udevd udevadm"


# we log what happen - xen-tools 24-setup-initramfs autoinstall hook
test -d /var/log/xen-tools || mkdir -p /var/log/xen-tools/
touch /var/log/xen-tools/initramfs.log

# functions
function copy() {

       test -r $1 &&  cp -fp $1 $2  >> /var/log/xen-tools/initramfs.log 2>&1
}

function copyusrbin() {

        test -r $1 && cp -fp $1 $2 >> /var/log/xen-tools/initramfs.log 2>&1
}

function copyall() {

       test -r $1 &&  cp -rfp $1 $2 >> /var/log/xen-tools/initramfs.log 2>&1
}

function cleanup() {
# cleanup workdir and unsorted
        rm -rf $WDIR $unsorted
}

function make_initramfs() {

( cd $WDIR ; find . | $CPIOBIN -o -H newc --quiet | $GZIPBIN -9 ) > $INITRAMFS_FILE

}

if [ -n "$KERNEL_VERSION" ] && [ ! -d "/lib/modules/$1" ] ; then
  echo "No modules directory named $1"
  exit 1
fi

function msg_start(){
printf "Creating $INITRAMFS_FILE... "
printf " \n \n"
}

function msg_end(){
printf "Creating $INITRAMFS_FILE completed..."
printf " \n \n"
}



# Systemd installs udevadm in /bin. Other udev implementations have it in /sbin
msg_start
#
if [ -x /sbin/udevadm ] ; then binfiles="$binfiles"; fi


# Create base directory structure
mkdir -p $WDIR/{bin,dev,lib/firmware,run,sbin,sys,proc,usr/share/mkinitramfs,usr/bin,usr/sbin}
mkdir -p $WDIR/etc/{modprobe.d,udev/rules.d}
touch $WDIR/etc/modprobe.d/modprobe.conf
ln -s lib $WDIR/lib64

# Create necessary device nodes
mknod -m 640 $WDIR/dev/console c 5 1
mknod -m 664 $WDIR/dev/null    c 1 3
mknod -m 664 $WDIR/dev/tty     c 5 0
mknod -m 664 $WDIR/dev/tty1    c 4 1
mknod -m 664 $WDIR/dev/vcs     c 7 0
mknod -m 664 $WDIR/dev/vcsa    c 7 128
mknod -m 664 $WDIR/dev/xvda    b 202 0
mknod -m 664 $WDIR/dev/loop0   b 7 0

# Install the udev configuration files
if [ -f /etc/udev/udev.conf ]; then
  copy /etc/udev/udev.conf $WDIR/etc/udev/udev.conf
fi

for file in $(find /etc/udev/rules.d/ -type f) ; do
  copy $file $WDIR/etc/udev/rules.d
done

# Install any firmware present
 copyall /lib/firmware $WDIR/lib

# Copy the RAID configuration file if present
if [ -f /etc/mdadm.conf ] ; then
  copy /etc/mdadm.conf $WDIR/etc
fi

# Install the init file
install -m0755 $DATADIR/$INITIN $WDIR/init

if [  -n "$KERNEL_VERSION" ] ; then
  if [ -x /usr/bin/kmod ] ; then
    binfiles="$binfiles kmod"
  else
    binfiles="$binfiles lsmod"
    sbinfiles="$sbinfiles insmod"
  fi
fi

# Install basic binaries
for f in $binfiles ; do
  ldd /usr/bin/$f | sed "s/\t//" | cut -d " " -f1 >> $unsorted
  copy $f $WDIR/usr/bin
done

# Add lvm if present
if [ -x /sbin/lvm ] ; then sbinfiles="$sbinfiles lvm dmsetup"; fi

for f in $sbinfiles ; do
  ldd /sbin/$f | sed "s/\t//" | cut -d " " -f1 >> $unsorted
  copy $f $WDIR/sbin
done

# Add udevd libraries if not in /sbin
if [ -x /lib/udev/udevd ] ; then
  ldd /lib/udev/udevd | sed "s/\t//" | cut -d " " -f1 >> $unsorted
elif [ -x /lib/systemd/systemd-udevd ] ; then
  ldd /usr/lib/systemd/systemd-udevd | sed "s/\t//" | cut -d " " -f1 >> $unsorted
fi

# Add module symlinks if appropriate
if [ -n "$KERNEL_VERSION" ] && [ -x /usr/bin/kmod ] ; then
  ln -s kmod $WDIR/bin/lsmod
  ln -s kmod $WDIR/bin/insmod
fi

# Add lvm symlinks if appropriate
# Also copy the lvm.conf file
if  [ -x /sbin/lvm ] ; then
  ln -s lvm $WDIR/sbin/lvchange
  ln -s lvm $WDIR/sbin/lvrename
  ln -s lvm $WDIR/sbin/lvextend
  ln -s lvm $WDIR/sbin/lvcreate
  ln -s lvm $WDIR/sbin/lvdisplay
  ln -s lvm $WDIR/sbin/lvscan

  ln -s lvm $WDIR/sbin/pvchange
  ln -s lvm $WDIR/sbin/pvck
  ln -s lvm $WDIR/sbin/pvcreate
  ln -s lvm $WDIR/sbin/pvdisplay
  ln -s lvm $WDIR/sbin/pvscan

  ln -s lvm $WDIR/sbin/vgchange
  ln -s lvm $WDIR/sbin/vgcreate
  ln -s lvm $WDIR/sbin/vgscan
  ln -s lvm $WDIR/sbin/vgrename
  ln -s lvm $WDIR/sbin/vgck
  # Conf file(s)
  copyall /etc/lvm $WDIR/etc
fi

# Install libraries
sort $unsorted | uniq | while read library ; do
  if [ "$library" == "linux-vdso.so.1" ] ||
     [ "$library" == "linux-gate.so.1" ]; then
    continue
  fi

  copy $library $WDIR/lib/ >> /var/log/xen-tools/initramfs.log 2>&1
done

if [ -d /lib/udev ]; then
  copyall /lib/udev $WDIR/lib/ >> /var/log/xen-tools/initramfs.log 2>&1
fi
if [ -d /lib/systemd ]; then
  copyall /lib/systemd $WDIR/lib/ >> /var/log/xen-tools/initramfs.log 2>&1
fi

# Install the kernel modules if requested
if [ -n "$KERNEL_VERSION" ]; then
  find                                                                        \
     /lib/modules/$KERNEL_VERSION/kernel/{crypto,fs,lib}                      \
     /lib/modules/$KERNEL_VERSION/kernel/drivers/{block,ata,md,firewire}      \
     /lib/modules/$KERNEL_VERSION/kernel/drivers/{scsi,message,xen,block,virtio,base,rtc} \
     /lib/modules/$KERNEL_VERSION/kernel/drivers/usb/{host,storage}           \
     -type f 2> /dev/null | cpio --make-directories -p --quiet $WDIR >> /var/log/xen-tools/initramfs.log 2>&1

  copy /lib/modules/$KERNEL_VERSION/modules.{builtin,order}                     \
            $WDIR/lib/modules/$KERNEL_VERSION >> /var/log/xen-tools/initramfs.log 2>&1

  depmod -b $WDIR $KERNEL_VERSION >> /var/log/xen-tools/initramfs.log 2>&1
fi

# make the initramfs
make_initramfs >> /var/log/xen-tools/initramfs.log 2>&1

# Remove the temporary directory and file
cleanup

msg_end
#
# EOF
